name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: jmp1
      id: jmp1
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 0
        setup-command: sudo -H pip3 install -r requirements.txt
    - name: jmp2
      id: jmp2
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: ''
    - name: jmp3
      id: jmp3
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        JMP1_RESULTS: "${{steps.jmp1.outputs.result}}"
        JMP2_RESULTS: "${{steps.jmp2.outputs.result}}"
        JMP3_RESULTS: "${{steps.jmp3.outputs.result}}"
      with:
        runners: jmp1,jmp2,jmp3
